---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2020-8-11 9:09
---

local MoveData = {}

local pos = "pos"
local x = "x"
local y = "y"
local z = "z"

local offset = "offset"

MoveData[pos] = {}
MoveData[pos][x] = 2
MoveData[pos][y] = 3
MoveData[pos][z] = 4

MoveData[offset] = 2.15

return MoveData